### PR TITLE
Huge overhaul

### PR DESCRIPTION
**Pull request by DerekTurtleRoe**
Basically I updated, changed, or improved everything. Not enough for it to change the goal of the project or push it in a new direction or anything, just take the functionality it had and make it way better.

First, I updated all the libraries to the latest version. That alone fixed many problems with various web browsers and improved performance.

Second, I optimized all the libraries by using the minified versions, then removing any unnecessary fluff. This improved performance as well.

Thirdly, I updated the HTML to be fully HTML5 compliant, and also made some optimizations to the HTML. This improved performance and compatibility with older browsers.

Fourthly (are these even real words?), I made some cosmetic and visual improvements to the readme, and the HTML as well.

Fifthly (they aren't), I updated the wording of some things for clarification and also fixed some grammatical errors.

Lastly, I localized the JavaScript and gave it its own folder. This might seem like an issue, but it will better in the long term due to the fact that it will make upgrading libraries easier, as well as making it impossible for the site to be down if one of the libraries' websites goes down or is under maintenance. This will insure the project can have an uninterrupted BIOS verification system for users and developers.

I hope you like all the changes. I use this tool pretty frequently, actually. About time we had something like it!

I plan on adding all the rest of the Sega Dreamcast BIOS hashes and files to the code soon as well.

Here are the other hashes in case you are interested:

screenshot 1

Any questions or comments are welcome.

### CODE REVIEW

**Comment by DerekTurtleRoe** [comment]
Actually, I was going to add a .gitattributes and a .gitignore, but I wanted your permission to do so before I did. I would like your input as far as that goes.

**Comment by skmp** [comment]
Hey, nice to see someone else interested in this idea!

I'll be extremely busy the coming days (warping up r7, site updates, and some irl mess) but i'll try to give you feedback before Monday.

**Comment by DerekTurtleRoe** [comment]
Alright. I may add a few more things, then I want to move on to VMU.js and the Reicast Web UI. I have a few ideas about Reicast itself in terms of improvements, but I want to work my way up to that. :smile:

**Comment by DerekTurtleRoe** [comment]
I saw the new website, it looks great! The automated testing videos were actually pretty cool too. I wish I could do that with my projects. :laughing:

**Comment by skmp** [comment]
Okay, I got a couple of mins free today. It's been a chaotic week

## I agree with
- Moving the libs (I was lazy)
- Updated readme/etc
- My back is indeed no longer in pain :+1: 
- Adding CRC
- Syncing with mame/etc

## I disagree with
- removing whitespace
  I prefer to keep the html/js/css formating though, it just adds a few bytes and makes the code easy to read. If this ever becomes popular enough there are automatic magnification tools to help.
- Shortening the hashes
  I love secure hashes. For less text size only the frist 10 chars can be displayed, with ... or something. You don't really need to read them (or something) anyway. The idea is to collect all hashes for all the files though, so we can cross check with other projects  (ex, mame, demul)

Doh, the site was broken over the move to https. Lol.

**Comment by DerekTurtleRoe** [comment]
Alright, all that seems fair. Let me change the whitespace. Did you want the JavaScript formatted too? Since they are external libraries I mean? The HTML/CSS I am formatting now.

Also I have a program which can hash using a TON of different algorithms, I can start calculating using the different ones and upload them as a separate file, or include them in a comment or something. I just recently got my hands on dumped BIOS files from multiple Dreamcast systems (including two different development systems). I'm writing a Dreamcast emulator called TurtleDC and I am using it for research. Anyway, tell me what you think of that stuff too.

**Comment by baka0815** [comment]
Is this still relevant?

**Comment by DerekTurtleRoe** [comment]
@baka0815 Not really, I don't think, at this point, I think it would all need to be updated again and reformatted.

**Pull request closed without merging**
